allowBuilds:
  '@prisma/client': false
  '@prisma/engines': false
  better-sqlite3: false
  esbuild: set this to true or false
  prisma: false
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
